export const nonConflictingEventsData = [
  [
    {
      id: 1,
      startTime: "00:00",
      endTime: "01:30",
      color: "#f6be23",
      title: "#DevMeetCollab",
    },
    {
      id: 2,
      startTime: "4:30",
      endTime: "7:30",
      color: "#f6501e",
      title: "#DevMeetCollab",
    },
    {
      id: 3,
      startTime: "12:00",
      endTime: "13:30",
      color: "#029be5",
      title: "#DevMeetCollab",
    },
    {
      id: 4,
      startTime: "9:00",
      endTime: "10:00",
      color: "#029be5",
      title: "#DevMeetCollab",
    },
    {
      id: 5,
      startTime: "16:00",
      endTime: "19:00",
      color: "#029be5",
      title: "#DevMeetCollab",
    },
    {
      id: 6,
      startTime: "20:30",
      endTime: "22:30",
      color: "#029be5",
      title: "#DevMeetCollab",
    },
  ],
];

export const conflictingEventsData = [
  [
    {
      id: 1,
      startTime: "00:00",
      endTime: "01:30",
      color: "#f6be23",
      title: "#DevMeetCollab",
    },
    {
      id: 2,
      startTime: "3:30",
      endTime: "7:30",
      color: "#e99c85",
      title: "#DevMeetCollab",
    },
    {
      id: 3,
      startTime: "4:30",
      endTime: "8:30",
      color: "#f6501e",
      title: "#DevMeetCollab",
    },
    {
      id: 4,
      startTime: "6:30",
      endTime: "9:00",
      color: "#6271af",
      title: "meetting with team",
    },
    {
      id: 5,
      startTime: "11:00",
      endTime: "13:30",
      color: "#3d9b3a",
      title: "#DevMeetCollab",
    },
    {
      id: 6,
      startTime: "12:00",
      endTime: "13:30",
      color: "#c55ec4",
      title: "#DevMeetCollab",
    },
    {
      id: 7,
      startTime: "9:30",
      endTime: "10:30",
      color: "#029be5",
      title: "#DevMeetCollab",
    },
    {
      id: 8,
      startTime: "16:00",
      endTime: "17:00",
      color: "#ed6f2b",
      title: "#DevMeetCollab",
    },
    {
      id: 9,
      startTime: "15:00",
      endTime: "17:00",
      color: "#d7557b",
      title: "#DevMeetCollab",
    },
    {
      id: 10,
      startTime: "18:00",
      endTime: "19:00",
      color: "#f6501e",
      title: "#DevMeetCollab",
    },
    {
      id: 11,
      startTime: "20:30",
      endTime: "22:30",
      color: "#d7b97a",
      title: "#DevMeetCollab",
    },
    {
      id: 12,
      startTime: "20:30",
      endTime: "22:30",
      color: "#029be5",
      title: "#DevMeetCollab",
    },
  ],
  [],
  [
    {
      id: 1,
      startTime: "00:00",
      endTime: "01:00",
      color: "#f6be23",
      title: "#DevMeetCollab",
    },
    {
      id: 2,
      startTime: "3:10",
      endTime: "3:15",
      color: "#e99c85",
      title: "#DevMeetCollab",
    },
    {
      id: 3,
      startTime: "4:39",
      endTime: "5:45",
      color: "#f6501e",
      title: "#DevMeetCollab",
    },
    {
      id: 4,
      startTime: "11:30",
      endTime: "12:00",
      color: "#6271af",
      title: "meetting with team",
    },
    {
      id: 5,
      startTime: "13:00",
      endTime: "13:30",
      color: "#3d9b3a",
      title: "#DevMeetCollab",
    },
    {
      id: 6,
      startTime: "08:00",
      endTime: "9:45",
      color: "#c55ec4",
      title: "#DevMeetCollab",
    },
    {
      id: 7,
      startTime: "23:15",
      endTime: "23:50",
      color: "#029be5",
      title: "#DevMeetCollab",
    },
    {
      id: 8,
      startTime: "17:00",
      endTime: "18:30",
      color: "#ed6f2b",
      title: "#DevMeetCollab",
    },
    {
      id: 9,
      startTime: "16:00",
      endTime: "17:30",
      color: "#d7557b",
      title: "#DevMeetCollab",
    },
    {
      id: 10,
      startTime: "19:00",
      endTime: "20:00",
      color: "#f6501e",
      title: "#DevMeetCollab",
    },
    {
      id: 11,
      startTime: "20:30",
      endTime: "22:30",
      color: "#d7b97a",
      title: "#DevMeetCollab",
    },
    {
      id: 12,
      startTime: "20:35",
      endTime: "21:45",
      color: "#029be5",
      title: "#DevMeetCollab",
    },
  ],
];

export const availableTimesForBackground = [
  { time: "00 AM", id: "startTime" },
  { time: "01 AM", id: 1 },
  { time: "02 AM", id: 2 },
  { time: "03 AM", id: 3 },
  { time: "04 AM", id: 4 },
  { time: "05 AM", id: 5 },
  { time: "06 AM", id: 6 },
  { time: "07 AM", id: 7 },
  { time: "08 AM", id: 8 },
  { time: "09 AM", id: 9 },
  { time: "10 AM", id: 10 },
  { time: "11 AM", id: 11 },
  { time: "12 PM", id: 12 },
  { time: "1 PM", id: 13 },
  { time: "2 PM", id: 14 },
  { time: "3 PM", id: 15 },
  { time: "4 PM", id: 16 },
  { time: "5 PM", id: 17 },
  { time: "6 PM", id: 18 },
  { time: "7 PM", id: 19 },
  { time: "8 PM", id: 20 },
  { time: "9 PM", id: 21 },
  { time: "10 PM", id: 22 },
  { time: "11 PM", id: 23 },
  { time: "", id: "endTime" },
];
